package it.ciroppina.idol.generic.tunnel.wsclient;

import java.util.HashMap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2016-01-27T11:00:06.952+01:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", name = "IdolOEMTunnel")
@XmlSeeAlso({ObjectFactory.class})
public interface IdolOEMTunnel {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "autnResponseAsList", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.AutnResponseAsList")
    @WebMethod
    @ResponseWrapper(localName = "autnResponseAsListResponse", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.AutnResponseAsListResponse")
    public java.util.List<Hit> autnResponseAsList(
        @WebParam(name = "arg0", targetNamespace = "")
        HashMap<String, String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getHitIndexedContent", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetHitIndexedContent")
    @WebMethod
    @ResponseWrapper(localName = "getHitIndexedContentResponse", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetHitIndexedContentResponse")
    public java.lang.String getHitIndexedContent(
        @WebParam(name = "arg0", targetNamespace = "")
        HashMap<String, String> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getQueryHitsMap", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetQueryHitsMap")
    @WebMethod
    @ResponseWrapper(localName = "getQueryHitsMapResponse", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetQueryHitsMapResponse")
    public java.util.List<Hit> getQueryHitsMap(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getlicenseinfo", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.Getlicenseinfo")
    @WebMethod
    @ResponseWrapper(localName = "getlicenseinfoResponse", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetlicenseinfoResponse")
    public java.lang.String getlicenseinfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getstatus", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.Getstatus")
    @WebMethod
    @ResponseWrapper(localName = "getstatusResponse", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetstatusResponse")
    public java.lang.String getstatus();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "grl", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.Grl")
    @WebMethod
    @ResponseWrapper(localName = "grlResponse", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GrlResponse")
    public java.lang.String grl(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "categorySuggestFromText", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.CategorySuggestFromText")
    @WebMethod
    @ResponseWrapper(localName = "categorySuggestFromTextResponse", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.CategorySuggestFromTextResponse")
    public ResultList categorySuggestFromText(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSpellCheck", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetSpellCheck")
    @WebMethod
    @ResponseWrapper(localName = "getSpellCheckResponse", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetSpellCheckResponse")
    public java.util.List<java.lang.String> getSpellCheck(
        @WebParam(name = "arg0", targetNamespace = "")
        HashMap<String, String> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "autnResponseAsString", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.AutnResponseAsString")
    @WebMethod
    @ResponseWrapper(localName = "autnResponseAsStringResponse", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.AutnResponseAsStringResponse")
    public java.lang.String autnResponseAsString(
        @WebParam(name = "arg0", targetNamespace = "")
        HashMap<String, String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getQueryResponse", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetQueryResponse")
    @WebMethod
    @ResponseWrapper(localName = "getQueryResponseResponse", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetQueryResponseResponse")
    public java.lang.String getQueryResponse(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getQueryHitsNoDocumentMap", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetQueryHitsNoDocumentMap")
    @WebMethod
    @ResponseWrapper(localName = "getQueryHitsNoDocumentMapResponse", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetQueryHitsNoDocumentMapResponse")
    public java.util.List<Hit> getQueryHitsNoDocumentMap(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSpellCheckFields", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetSpellCheckFields")
    @WebMethod
    @ResponseWrapper(localName = "getSpellCheckFieldsResponse", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetSpellCheckFieldsResponse")
    public java.util.List<java.lang.String> getSpellCheckFields(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getversion", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.Getversion")
    @WebMethod
    @ResponseWrapper(localName = "getversionResponse", targetNamespace = "http://tunnel.generic.idol.ciroppina.it/", className = "it.ciroppina.idol.generic.tunnel.wsclient.GetversionResponse")
    public java.lang.String getversion();
}
