package it.ciroppina.idol.generic.tunnel.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2016-01-25T15:54:04.881+01:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "IdolOEMTunnel", 
                  wsdlLocation = "http://localhost:8080/idol.generic.tunnel/IdolOEMTunnel/IdolOEMTunnel?wsdl",
                  targetNamespace = "http://tunnel.generic.idol.ciroppina.it/") 
public class IdolOEMTunnel_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tunnel.generic.idol.ciroppina.it/", "IdolOEMTunnel");
    public final static QName IdolOEMTunnelPort = new QName("http://tunnel.generic.idol.ciroppina.it/", "IdolOEMTunnelPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/idol.generic.tunnel/IdolOEMTunnel/IdolOEMTunnel?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IdolOEMTunnel_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/idol.generic.tunnel/IdolOEMTunnel/IdolOEMTunnel?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IdolOEMTunnel_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IdolOEMTunnel_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdolOEMTunnel_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IdolOEMTunnel_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IdolOEMTunnel_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IdolOEMTunnel_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IdolOEMTunnel
     */
    @WebEndpoint(name = "IdolOEMTunnelPort")
    public IdolOEMTunnel getIdolOEMTunnelPort() {
        return super.getPort(IdolOEMTunnelPort, IdolOEMTunnel.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IdolOEMTunnel
     */
    @WebEndpoint(name = "IdolOEMTunnelPort")
    public IdolOEMTunnel getIdolOEMTunnelPort(WebServiceFeature... features) {
        return super.getPort(IdolOEMTunnelPort, IdolOEMTunnel.class, features);
    }

}
